name: MegaLinter

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main

permissions: read-all

jobs:
  build:
    name: MegaLinter
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: MegaLinter
        uses: megalinter/megalinter@v7
        env:
          DISABLE_LINTERS: SPELL_CSPELL
          FORMATTERS_DISABLE_ERRORS: false
          GITHUB_COMMENT_REPORTER: false
          GITHUB_STATUS_REPORTER: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRINT_ALPACA: false
          REPOSITORY_KICS_ARGUMENTS: --exclude-queries=555ab8f9-2001-455e-a077-f2d0f41e2fb9
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' }}
